services:
  
  db:
    image: postgres:latest
    restart: always
    container_name: users_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_database
    ports:
      - "5432:5432"
